# Generated by Django 4.2.4 on 2023-09-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_message", models.TextField()),
                ("estimate_complete_message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estimate_email", models.TextField()),
                ("estimate_phone", models.TextField()),
                ("form_email", models.TextField()),
                ("form_phone", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
