# Generated by Django 4.2.4 on 2023-09-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Dashboard", "0002_defaultresponse_notifications_delete_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="estimate_email",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="estimate_phone",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="form_email",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="form_phone",
            field=models.TextField(default=None, null=True),
        ),
    ]
