# Generated by Django 4.2.4 on 2023-09-27 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LeadCapture", "0010_alter_phonecall_receive_text_field"),
        (
            "Dashboard",
            "0004_rename_estimate_email_notifications_voicemail_email_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneCallInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.IntegerField()),
                ("voicemail", models.BooleanField(default=False)),
                ("voicemail_link", models.TextField(default=None, null=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LeadCapture.phonecall",
                    ),
                ),
            ],
        ),
    ]
