# Generated by Django 4.2.4 on 2023-09-27 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Dashboard", "0005_phonecallinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phonecallinfo",
            old_name="lead",
            new_name="call_num",
        ),
    ]
