# Generated by Django 4.2.4 on 2023-10-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LeadCapture", "0011_rename_datetime_field_phonecall_datetime"),
        ("Dashboard", "0006_rename_lead_phonecallinfo_call_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadDisplay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.TextField()),
                ("name", models.TextField()),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LeadCapture.lead",
                    ),
                ),
            ],
        ),
    ]
