# Generated by Django 4.2.4 on 2023-08-12 20:16

from django.db import migrations


def set_form_default_false(apps, schema_editor):
    Message = apps.get_model("LeadCapture", "Message")
    Message.objects.filter(form__isnull=True).update(form=False)


def revert_set_form_default_false(apps, schema_editor):
    # Revert the operation if needed
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("LeadCapture", "0003_message_form"),
    ]

    operations = [
        migrations.RunPython(set_form_default_false, revert_set_form_default_false),
    ]
