# Generated by Django 4.2.4 on 2023-09-15 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LeadCapture", "0005_phonecall"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APIKey",
        ),
    ]
