# Generated by Django 4.2.4 on 2023-09-20 14:20

from django.db import migrations, models


def set_deleted_to_false(apps, schema_editor):
    FormQuestion = apps.get_model("LeadCapture", "FormQuestion")
    FormQuestion.objects.all().update(deleted=False)


class Migration(migrations.Migration):
    dependencies = [
        ("LeadCapture", "0006_delete_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="formquestion",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_deleted_to_false),
    ]
