# Generated by Django 4.2.4 on 2023-09-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LeadCapture", "0008_delete_phonecall"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_field", models.TextField()),
                ("call_sid", models.TextField()),
                ("datetime_field", models.DateTimeField()),
                ("receive_text_field", models.BooleanField()),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LeadCapture.lead",
                    ),
                ),
            ],
        ),
    ]
