# Generated by Django 4.2.4 on 2023-09-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LeadCapture", "0009_phonecall"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonecall",
            name="receive_text_field",
            field=models.BooleanField(default=False),
        ),
    ]
