# Generated by Django 4.2.4 on 2023-10-03 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LeadCapture", "0010_alter_phonecall_receive_text_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phonecall",
            old_name="datetime_field",
            new_name="datetime",
        ),
    ]
