# Generated by Django 4.2.4 on 2023-10-27 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("LeadCapture", "0013_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="formquestion",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
